services:
  db:
    image: crpi-2zg9hvsh8g8vjhbv.cn-shenzhen.personal.cr.aliyuncs.com/kayzee3327/mysql:lts  # 替换为你的MySQL镜像名称
    platform: linux/amd64
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=library_management
      - TZ=Asia/Shanghai 
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:  # 可选健康检查
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    expose:
      - 33060

  web:
    build: .
    platform: linux/amd64
    ports:
      - "8000:5000"  # 映射宿主机5000端口到容器5000端口
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=library_management
      - DB_PORT=3306
      - TZ=Asia/Shanghai
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network


volumes:
  mysql-data:

networks:
  app-network: